myOCR = require("OCR_model");
console.time("加载")
var OCR = myOCR.prepare()
console.timeEnd("加载")
launch("com.tencent.mobileqq")
sleep(2000)
console.time("截图")
requestScreenCapture()
myImage = captureScreen()
// myImage = $automator.takeScreenshot()
console.timeEnd("截图")
console.time("识别")
var OCR_Result = OCR.loadImage(myImage);
console.timeEnd("识别")
myImage.recycle()
console.time("点击文字")
myOCR.findText(OCR_Result, "高危版", "click")
console.timeEnd("点击文字")